name: iris_websocket
description: A extra light package to websocket on Flutter (Android, iOS, Web, Windows, Mac and Linux)
version: 1.2.1
#homepage: 

# from: https://github.com/jonataslaw/getsocket
# last update: 1401-08-04

environment:
  sdk: ">=2.15.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter: