name: iris_websocket
description: A extra light package to websocket on Flutter (Android, iOS, Web, Windows, Mac and Linux)
version: 1.4.3
#homepage: 

# from: https://github.com/jonataslaw/getsocket

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"


dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter: